name: Continuous Integration
on: 
  push:
    branches:
     - main
  pull_request:

jobs:
  test-job:
  # CI Validation: Temporary job to verify GitHub Action triggers.
    runs-on: ubuntu-latest
    steps:
      - name: Successful test
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
  
  test-makefile:
    name: build and test makefile
    runs-on: ubuntu-latest
    env:
      PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
      PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make tar diffutils bzip2 gzip curl git
      - name: run make
        run: make

  test-fedora:
  #Only testing on Fedora latest for now, Will later include other versions and platforms 
    name: build and test on Fedora latest
    runs-on: ubuntu-latest
    container:
      image: quay.io/fedora/fedora:latest
      options: --user root
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set PR commit range for git-validation
        if: github.event_name == 'pull_request'
        run: |
          echo "PR_BASE_SHA=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
          echo "PR_HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
      - name: Install dependencies (using dnf, Fedora's package manager)
        run: |
          dnf update -y
          dnf install -y golang make tar diffutils bzip2 gzip curl git which
      - name: Build and test
        run: make

